### ISSUE TITLE
Ignore CI when only `docs/proposal` is changed.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#4685]
Can use this yml config:
```
on:
  push:
    paths-ignore:
      - 'docs/proposals/**'
 ```
