### ISSUE TITLE
Retry workflow cache download a few more times when failed

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#5201]
CI workflow is still unstable.
It currently fails on the cache restore because the server is busy.
Then, the CI logic starts to locally build slang-llvm but it also fails because git cloning failed; probably because the server is busy again.

We like to retry the cache restore a few more times when failed.
And we can also retry to clone the repo when failed.

**Comment by jkwak-work** [comment]
Currently the cache restore does the following,
```
    - uses: actions/cache/restore@v4
      id: cache-llvm
      if: inputs.build-llvm == 'true'
      with:
        path: ${{ github.workspace }}/build/llvm-project-install
        # Use os*compiler*platform in lieu of an ABI key here, which is what we really want
        key: llvm-${{ inputs.os }}-${{ inputs.compiler }}-${{ inputs.platform }}-${{ hashFiles('external/build-llvm.sh') }}
```

We can do something like the following,
```
    # First try
    - name: First attempt to restore cache
      uses: actions/cache/restore@v4
      id: cache-llvm-first
      if: inputs.build-llvm == 'true'
      with:
        path: ${{ github.workspace }}/build/llvm-project-install
        key: llvm-${{ inputs.os }}-${{ inputs.compiler }}-${{ inputs.platform }}-${{ hashFiles('external/build-llvm.sh') }}
      continue-on-error: true

    # Second try if the first one failed
    - name: Second attempt to restore cache
      uses: actions/cache/restore@v4
      id: cache-llvm-second
      if: inputs.build-llvm == 'true' && steps.cache-llvm-first.outcome != 'success'
      with:
        path: ${{ github.workspace }}/build/llvm-project-install
        key: llvm-${{ inputs.os }}-${{ inputs.compiler }}-${{ inputs.platform }}-${{ hashFiles('external/build-llvm.sh') }}
```
