### ISSUE TITLE
Update the workflow YAML files based on the recent changes

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#5686]
Recently we renamed a few files and directories and they should be reflected on the workflow YAML files.
 - `LICENCE` is a typo of `LICENSE`.
 - We recently created a new "LICENSES/"
 - CONTRIBUTION.md was renamed to CONTRIBUTING.md

```
on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "LICENCE"
      - "CONTRIBUTION.md"
      - "README.md"
```
